"""Confluence source: real Confluence Cloud REST API (CQL search),
authenticated with the user's own API token (email + token, Basic auth) -
generated by the user at id.atlassian.com/manage-profile/security/api-tokens,
not a service account. Uses httpx directly rather than atlassian-python-api,
which is a synchronous library and would block the event loop.
"""

from __future__ import annotations

import os
import re
from datetime import datetime
from typing import Any

import httpx

from columbo_py.config import SETTINGS
from columbo_py.engine.search.result import Options, Result
from columbo_py.engine.search.source import Capabilities
from columbo_py.sources.guidance import load_guidance

KIND_DESCRIPTION = load_guidance(__file__)

_HTML_TAG_RE = re.compile(r"<[^>]+>")

# The planner is instructed (via GUIDANCE.md) to write full CQL. This detects
# whether it did: a CQL clause always contains a field operator. If none is
# present the model fell back to bare keywords, which we wrap as a text clause.
_CQL_HINT_RE = re.compile(r"(~|!=|>=|<=|=|>|<|\bAND\b|\bOR\b|\bNOT\b|\bIN\b|\bORDER BY\b)", re.I)


def _looks_like_cql(query: str) -> bool:
    return bool(_CQL_HINT_RE.search(query))


def _escape_cql_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _strip_html(html: str) -> str:
    """Confluence's storage/view body formats are HTML; a rough tag-strip is
    good enough for LLM consumption without pulling in a full HTML parser."""
    return _HTML_TAG_RE.sub(" ", html)


class ConfluenceSource:
    def __init__(
        self,
        base_url: str | None = None,
        email: str | None = None,
        api_token: str | None = None,
    ) -> None:
        self._base_url = (base_url or os.environ.get("CONFLUENCE_BASE_URL", "")).rstrip("/")
        self._email = email or os.environ.get("CONFLUENCE_EMAIL")
        self._api_token = api_token or os.environ.get("CONFLUENCE_API_TOKEN")
        self._client: httpx.AsyncClient | None = None

    def name(self) -> str:
        return "confluence"

    def kind(self) -> str:
        return KIND_DESCRIPTION

    def capabilities(self) -> Capabilities:
        return Capabilities(
            filters=(), supports_days=True, supports_author=True, supports_scope=True, max_limit=100
        )

    async def initialize(self) -> None:
        if self._client is not None:
            return
        if not (self._base_url and self._email and self._api_token):
            raise RuntimeError(
                "Confluence not configured: set CONFLUENCE_BASE_URL "
                "(e.g. https://yourcompany.atlassian.net/wiki), "
                "CONFLUENCE_EMAIL, and CONFLUENCE_API_TOKEN "
                "(generate one at https://id.atlassian.com/manage-profile/security/api-tokens)."
            )
        self._client = httpx.AsyncClient(
            base_url=self._base_url,
            auth=(self._email, self._api_token),
            headers={"Accept": "application/json"},
            timeout=SETTINGS.http.default_timeout_s,
        )

    def _to_cql(self, query: str) -> str:
        """Pass the planner's query through as CQL. If it wrote bare keywords
        (no CQL operator), wrap them in a `text ~ "..."` clause so the query
        is still valid - CQL requires a text/title clause."""
        if _looks_like_cql(query):
            return query
        return f'text ~ "{_escape_cql_string(query)}"'

    async def search(self, query: str, opts: Options) -> list[Result]:
        if self._client is None:
            await self.initialize()
        assert self._client is not None

        response = await self._client.get(
            "/rest/api/content/search",
            params={
                "cql": self._to_cql(query),
                "limit": min(opts.limit, 100),
                "expand": "body.view,space,history",
            },
        )
        response.raise_for_status()
        payload = response.json()
        return [self._page_to_result(page) for page in payload.get("results", [])]

    async def lookup(self, term: str) -> Result | None:
        """`term` is a page title, optionally scoped as "SPACE:Title"."""
        if self._client is None:
            await self.initialize()
        assert self._client is not None

        space, _, title = term.partition(":") if ":" in term else (None, "", term)
        cql = f'title = "{title}"' + (f' AND space = "{space}"' if space else "")
        response = await self._client.get(
            "/rest/api/content/search",
            params={"cql": cql, "limit": 1, "expand": "body.view,space,history"},
        )
        response.raise_for_status()
        results = response.json().get("results", [])
        return self._page_to_result(results[0]) if results else None

    def _page_to_result(self, page: dict[str, Any]) -> Result:
        body_html = page.get("body", {}).get("view", {}).get("value", "")
        updated = page.get("history", {}).get("lastUpdated", {}).get("when")
        # Only build a permalink if the page's webui link is present; without
        # it, "{base}{}" would collapse to the wiki root - a misleading URL
        # that looks valid but points at the wrong page. None is safer.
        webui = page.get("_links", {}).get("webui")
        permalink = f"{self._base_url}{webui}" if webui else None
        return Result(
            source="confluence",
            id=page["id"],
            title=page.get("title", ""),
            content=_strip_html(body_html).strip(),
            timestamp=datetime.fromisoformat(updated) if updated else None,
            permalink=permalink,
            metadata={"space": page.get("space", {}).get("key")},
        )
